### ISSUE TITLE
ProgramError: 100: 8 byte instruction identifier not provide/  Transaction simulation failed: Error processing Instruction 0: custom program error: 0x64

### ISSUE THREAD

**Issue by MatthewTang** [project-serum/anchor#1062]
[🚨noob alert] Hi guys, I am following along buildspace's Solana project, and ran into this error , any ideas as to what might be the cause to this ? Literally can't find anything regarding this error on Google ... am I missing anything ? Thanks in advance 🙏

remark: 
I am running a validator separately on another terminal using`solana-test-validator --no-bpf-jit`
my machine is a M1 mac
anchor-cli 0.18.0
node 17.0.1
solana-cli 1.8.2 (src:devbuild; feat:52865992)

command that I ran: `anchor test --skip-local-validator`

ouput:
```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x64 
    Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN invoke [1]
    Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN consumed 592 of 200000 compute units
    Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN failed: custom program error: 0x64
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x64
    at Connection.sendEncodedTransaction (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@solana/web3.js/lib/index.cjs.js:6591:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@solana/web3.js/lib/index.cjs.js:6550:20)
    at async sendAndConfirmRawTransaction (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@solana/web3.js/lib/index.cjs.js:8513:21)
    at async Provider.send (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@project-serum/anchor/dist/cjs/provider.js:85:22)
    at async Object.rpc [as addGif] (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
    at async main (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/tests/myepicproject.js:34:3)
    at async runMain (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/tests/myepicproject.js:46:5) {
  logs: [
    'Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN invoke [1]',
    'Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN consumed 592 of 200000 compute units',
    'Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN failed: custom program error: 0x64'
  ]
}
ProgramError: 100: 8 byte instruction identifier not provided
    at Function.parse (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@project-serum/anchor/dist/cjs/error.js:40:20)
    at Object.rpc [as addGif] (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/tests/myepicproject.js:34:3)
    at async runMain (/Users/matthewtang/blockchain/buildspace/Solana/myepicproject/tests/myepicproject.js:46:5) {
  code: 100,
  msg: '8 byte instruction identifier not provided'
}
```

programs/myepicproject/src/lib.rs
```
use anchor_lang::prelude::*;

declare_id!("AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN");

#[program]
pub mod myepicproject {
    use super::*;
    pub fn start_stuff_off(ctx: Context<StartStuffOff>) -> ProgramResult {
        // get a reference to the account.
        let base_account = &mut ctx.accounts.base_account;
        base_account.total_gifs = 0;
        Ok(())
    }

    pub fn add_gif(ctx: Context<AddGif>) -> ProgramResult {
        // get a reference to the account and increment total_gifs.
        //let base_account = &mut ctx.accounts.base_account;
        //base_account.total_gifs += 1;
        Ok(())
    }
}

#[derive(Accounts)]
pub struct StartStuffOff<'info> {
    #[account(init, payer = user, space = 9000)]
    pub base_account: Account<'info, BaseAccount>,
    #[account(mut)]
    pub user: Signer<'info>,
    pub system_program: Program <'info, System>,

}

// Specify what data you want in the AddGif context.
#[derive(Accounts)]
pub struct AddGif<'info> {
    #[account(mut)]
    pub base_account: Account <'info, BaseAccount>,
}


// tell solana what we want to store on this account
#[account]
pub struct BaseAccount {
    pub total_gifs: u64,
}
```

tests/myepicproject.js
```
const anchor = require("@project-serum/anchor");

const { SystemProgram } = anchor.web3;

const main = async () => {
  console.log("🚀 Starting test...");

  //const provider = anchor.Provider.env();
  const provider = anchor.Provider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.Myepicproject;

  // create an account keypair for our program to use.
  const baseAccount = anchor.web3.Keypair.generate();

  // call start_stuff_off, pass it the params it needs!
  const tx = await program.rpc.startStuffOff({
    accounts: {
      baseAccount: baseAccount.publicKey,
      user: anchor.getProvider().wallet.publicKey,
      systemProgram: SystemProgram.programId,
    },
    signers: [baseAccount],
  });

  console.log("Your transaction signature", tx);

  // fetch data from the account
  let account = await program.account.baseAccount.fetch(baseAccount.publicKey);
  console.log("👀 GIF Count", account.totalGifs.toString());

  // call add_gif
  await program.rpc.addGif({
    accounts: {
      baseAccount: baseAccount.publicKey,
    },
  });

  account = await program.account.baseAccount.fetch(baseAccount.publicKey);
  console.log("👀 GIF Count ", account.totalGifs.toString());
};

const runMain = async () => {
  try {
    await main();
    process.exit(0);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
};

runMain();
```

**Comment by fanatid** [comment]
@MatthewTang I had seen questions with this code in Discord, is your issue resolved?
https://discord.com/channels/889577356681945098/889702325231427584/913564632738856980

**Comment by MatthewTang** [comment]
@fanatid  hi, unfortunately not yet :( , although the code snippet looks very similar, the issue/ error mentioned in Discord is `custom program error: 0xa7`, or `Error: 167: the given account is not owned by the executing program` , which is different from the one that I've encountered.

**Comment by armaniferrante** [comment]
0xa7 is usually a result of one having an inconsistent `declare_id`. Make sure it's the same as what's deployed on your local network.

**Comment by MatthewTang** [comment]
hi @armaniferrante  thanks for your suggestion, but I think its the same, the declare_id in lib.rs is `declare_id!("AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN");` which is the same as the one in the error `'Program AF4htqheJyiBm64oYXfKcFKJ2XtaYieuKHVu399groQN failed: custom program error: 0x64'`, is this what you're referring to ? thanks

**Comment by torquan** [comment]
I'm running into the same issue.

Interestingly, this error message appears **after** the program terminated: the console output from 
```  console.log("👀 GIF Count ", account.totalGifs.toString());``` in the case from the code above is printed and a transaction signature is also printed.

Not sure what the transaction simulation even is?

**Comment by torquan** [comment]
I've dug a bit into it:

The error happens in `anchor/dist/cjs/program/namespace/rpc.js` in the line:
```
                const txSig = await provider.send(tx, ctx.signers, ctx.options);
```

the values for the parameters are:
tx:
```
Transaction {
  signatures: [],
  feePayer: undefined,
  instructions: [
    TransactionInstruction {
      keys: [Array],
      programId: [PublicKey],
      data: <Buffer dc 2b 99 d0 c2 bd 20 41>
    }
  ],
  recentBlockhash: undefined,
  nonceInfo: undefined
}
```

ctx.signer and ctx.options are undefined.

**Comment by torquan** [comment]
Reinstalling solana v1.8.5 solved the issue for me. 

Assuming this only applies to M1 people, you can do:

```bash
git clone https://github.com/solana-labs/solana.git/
```

```bash
cd solana
git checkout v1.8.5
```

```bash
./scripts/cargo-install-all.sh .
```

(see https://github.com/buildspace/buildspace-projects/edit/main/Solana_And_Web3/en/Section_2/Resources/m1_setup.md)

**Comment by fanatid** [comment]
@MatthewTang does the solution proposed by @torquan works for you?

**Comment by MatthewTang** [comment]
<img width="1515" alt="Screenshot 2021-11-27 at 11 40 26 AM" src="https://user-images.githubusercontent.com/40652107/143666909-c4f71feb-3ea4-45e2-955c-6cf6005ce38d.png">

@fanatid  it works !!! Thanks a lot 🙏 @torquan

**Comment by haomaaax** [comment]
it also works for me as M1 mac bro, thanks.

**Comment by yenicelik** [comment]
hmm I'm getting the same issue with solana 1.8.12. Is this a common thing or likely to be fixed soon? I can't imagine that one should stick to an older solana version because of this issue xD
