### ISSUE TITLE
Anchor Test

### ISSUE THREAD

**Issue by tayab2468** [project-serum/anchor#1063]
anchor test command gave me this error

Error: Error loading workspace IDL for serum_dex
    at /home/talha/Work/solana/solana-swap-test/swap/node_modules/@project-serum/anchor/dist/cjs/workspace.js:95:19
    at Array.forEach (<anonymous>)
    at attachWorkspaceOverride (/home/talha/Work/solana/solana-swap-test/swap/node_modules/@project-serum/anchor/dist/cjs/workspace.js:86:33)
    at Object.get (/home/talha/Work/solana/solana-swap-test/swap/node_modules/@project-serum/anchor/dist/cjs/workspace.js:78:17)
    at Suite.<anonymous> (/home/talha/Work/solana/solana-swap-test/swap/tests/swap.js:19:36)
    at Object.create (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/home/talha/Work/solana/solana-swap-test/swap/tests/swap.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
    at async singleRun (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/talha/Work/solana/solana-swap-test/swap/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.

**Comment by fanatid** [comment]
It's not possible to provide any valuable answer why `anchor test` fails for you without details of what are you doing. Please move you question to discord: https://discord.gg/sxy4zxBckh.
