### ISSUE TITLE
Anchor Js/Ts Clients Broken With Change To C Representation For ZeroCopy Accounts

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#1195]
# Overview

Previous code that was correctly able to fetch zerocopy accounts no longer works, or incorrectly parses accounts returning bad data. This issue is strictly related to the way the idl is either generated, or the js/ts clients interpret the idl, as parsing the account on-chain, and via rust code works.

When the account is unable to be parsed the error message is along the lines of the following, with the number `179` sometimes being different.

```
     Error: Invalid bool: 179
      at WrappedLayout.decodeBool [as decoder] (node_modules/@project-serum/borsh/src/index.ts:169:9)
      at WrappedLayout.decode (node_modules/@project-serum/borsh/src/index.ts:92:17)
      at Structure.decode (node_modules/buffer-layout/lib/Layout.js:1234:32)
      at Structure.decode (node_modules/buffer-layout/lib/Layout.js:1234:32)
      at AccountsCoder.decode (node_modules/@project-serum/anchor/src/coder/accounts.ts:53:19)
      at AccountClient.fetchNullable (node_modules/@project-serum/anchor/src/program/namespace/account.ts:153:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at AccountClient.fetch (node_modules/@project-serum/anchor/src/program/namespace/account.ts:165:18)
```

In the case of bad data being returned, a number such as `200000` being stored in a `u64` field is returned as `13979173243358019584`.

**Comment by armaniferrante** [comment]
Does your type contain padding bytes? Zero copy types shouldn't contain any.https://docs.rs/bytemuck/latest/bytemuck/trait.Pod.html#safety.

**Comment by bonedaddy** [comment]
Yea I think that's it. What kind of alignment is uses, 64bit ?

**Comment by bonedaddy** [comment]
Ah silly me the alignment was from the 2 `u8`. Thanks!
