### ISSUE TITLE
`SyntaxError: Unexpected token {`

### ISSUE THREAD

**Issue by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [project-serum/anchor#1262]
```
$ sudo npm i -g @project-serum/anchor-cli@0.20.0
/usr/local/bin/anchor -> /usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js
/usr/local/lib
└── @project-serum/anchor-cli@0.20.0 

$ anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ sudo anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
Linux x 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ sudo npm i -g @project-serum/anchor-cli@0.19.0
/usr/local/bin/anchor -> /usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js
/usr/local/lib
└── @project-serum/anchor-cli@0.19.0 

$ sudo anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ sudo npm i -g @project-serum/anchor-cli@0.18.2
/usr/local/bin/anchor -> /usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js
/usr/local/lib
└── @project-serum/anchor-cli@0.18.2 

$ anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ sudo anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ 


```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
```
$ do-release-upgrade -V
do-release-upgrade: version 18.04.45
$ do-release-upgrade
Checking for a new Ubuntu release
You have not rebooted after updating a package which requires a reboot. Please reboot before upgrading.
$ 

```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
```
$ sudo reboot 0
```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
After the reboot,

```
$ anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ sudo anchor --version
/usr/local/lib/node_modules/@project-serum/anchor-cli/anchor.js:69
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
$ 

```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
<h2 id="minimum-version-requirements" style="font-weight: 600; line-height: 1.25; font-size: 1.65rem; padding-bottom: 0.3rem; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: var(--borderColor); margin-top: -3.1rem; padding-top: 4.6rem; margin-bottom: 0px; color: rgb(44, 62, 80); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Minimum version requirements</h2>

```
Build tool | Version
Node.js | v11.0.0
```

https://project-serum.github.io/anchor/getting-started/installation.html#minimum-version-requirements

maybe this is the issue... will check

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
ok, after `do-release-upgrade` the vps instance broke & `sshd` did not respond. closing the issue.

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
Have been able to access it via DO console.

```
# anchor --version
anchor-cli 0.18.2
# node --version
v10.19.0
# lsb_release -d
Description:    Ubuntu 20.04.3 LTS
# 
```
