### ISSUE TITLE
Anchor build >> thread 'main' panicked at 'Not in workspace.'

### ISSUE THREAD

**Issue by SkyCandy2** [project-serum/anchor#1351]
**Issue:** Cannot get past this 'Not in workspace' issue. Can anyone help? 

**Terminal command:** `anchor build`

**Output:** 
`thread 'main' panicked at 'Not in workspace.', cli/src/lib.rs:701:47
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
`

**From cli/src/lib.rs:701:47:** 
`701.     let cfg = Config::discover(cfg_override)?.expect("Not in workspace.");`

**Versions:**
- git version 2.30.1
- solana-cli 1.9.1 
- anchor-cli 0.20.1  
- Node v16.13.2

**Comment by fanatid** [comment]
What is in the directory where you run `anchor build`?

**Comment by KnineVspython** [comment]
had the same thing go into the project folder my error changed but I still have this error
`Failed to obtain package metadata: `cargo metadata` exited with an error: error: failed to load manifest for workspace member `\\?\C:\Users\kamal\Desktop\solana betting\solana-anchor-betting--game\myepicproject\programs\*`

Caused by:
  failed to read `\\?\C:\Users\kamal\Desktop\solana betting\solana-anchor-betting--game\myepicproject\programs\*\Cargo.toml`

Caused by:
  The filename, directory name, or volume label syntax is incorrect. (os error 123)`

**Comment by JacobWarner** [comment]
I'm having the same error as @KnineVspython . I'm on Windows 11.

**Comment by fanatid** [comment]
@JoshuaBartels0311 can you clarify which `anchor` version are you use? (otherwise line can be wrong)

**Comment by fanatid** [comment]
Thanks for the quick reply! Can you also run `RUST_BACKTRACE=full anchor build`?

**Comment by nabeel99** [comment]
facing the same issue on windows 11, is there any workaround as of now ?

**Comment by KnineVspython** [comment]
> I'm having the same error as @KnineVspython . I'm on Windows 11.

https://github.com/KnineVspython/buildspace-projects/blob/main/Solana_And_Web3/en/Section_2/Resources/windows_setup.md  check this out man

**Comment by Suraj1001singh** [comment]
facing same as @SkyCandy2  is facing i am running anchor-cli 0.21.0 in windows 10
please provide solution asap!

**Comment by fanatid** [comment]
This backtrace is not so useful :( can you paste the backtrace for anchor cli build in debug mode?

**Comment by MukulGari** [comment]
> $ anchor build thread 'main' panicked at 'Not in workspace.', cli\src\lib.rs:750:47 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> Getting this aswell 😞
> 
> anchor-cli 0.24.2 solana-cli 1.9.1 cargo 1.60.0
> 
> Any solutions or suggestions?

bro u need to pass anchor build from inside the dir u made by anchor init

**Comment by swolswolomon** [comment]
anchor doesn't like dashes in folder names. underscores are fine.

**Comment by bubu59** [comment]
Hi guys, having this issue suddenly as well .... I have referred to previous links as well regarding `rustc --version` , `solana --version` as well... I'm not sure why this is happening suddenly as I have not had any issue for the past few months with other projects... Please help! 
![image](https://user-images.githubusercontent.com/74093051/187067914-696310f7-7e9d-46cc-bfa8-99510b8a54b3.png)

**Comment by bubu59** [comment]
alright, found a work around with my current issue and that is to `init` the new project in another current folder that anchor builds fine and turns out it works.... However, this should not be case right?

**Comment by troyistroyenzo** [comment]
Getting this too!:

thread 'main' panicked at 'Not in workspace.', cli\src\lib.rs:801:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

tried running it in its build space but to no avail

**Comment by cloakd** [comment]
just use `cargo build` instead

**Comment by akp111** [comment]
Running into the same error

**Comment by Individen** [comment]
It has already been mentioned in this thread that the error stems from not using `anchor init` first.  The official installation guide could do a better job of highlighting this as a necessary step. To summarize the fix for this issue:
1. `anchor init my_project` 
2. `cd my_project`
3. `anchor build`

**Comment by Lopestheve** [comment]
face same problem can someone gelp me IOS mac 

note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
Xs-MacBook-Pro:untitled1 x$ cd meu_projeto
Xs-MacBook-Pro:meu_projeto x$ anchor --version
anchor-cli 0.30.1
Xs-MacBook-Pro:meu_projeto x$ rustup install stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.84.1 (e71f9a9a9 2025-01-27)

info: checking for self-update
Xs-MacBook-Pro:meu_projeto x$ rustup default stable
info: using existing install for 'stable-x86_64-apple-darwin'
info: default toolchain set to 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.84.1 (e71f9a9a9 2025-01-27)

Xs-MacBook-Pro:meu_projeto x$ anchor build
thread 'main' panicked at cli/src/lib.rs:1367:47:
Not in workspace.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Xs-MacBook-Pro:meu_projeto x$ cargo build-bpf
error: no such command: `build-bpf`

**Comment by Individen** [comment]
I can't see that you used anchor init follow these steps:

   1. anchor init meu_projeto
   2. cd meu_projeto
   3. anchor build


Den fre 31 jan. 2025 00:33Lopestheve ***@***.***> skrev:
