### ISSUE TITLE
f32 or f64 arent supported in anchor idl

### ISSUE THREAD

**Issue by ExpLife0011** [project-serum/anchor#1353]
I have defined a field of type floating point in #[account], then run command "anchor test", got a error.

**IdlError: Type not found: {"name":"nums","type":{"defined":"f32"}}**
    at Function.fieldLayout (/mnt/d/it/work/blockchain/token-faucet/node_modules/@project-serum/anchor/src/coder/idl.ts:88:19)
    at /mnt/d/it/work/blockchain/token-faucet/node_modules/@project-serum/anchor/src/coder/idl.ts:116:28
    at Array.map (<anonymous>)
    at Function.typeDefLayout (/mnt/d/it/work/blockchain/token-faucet/node_modules/@project-serum/anchor/src/coder/idl.ts:115:48)
    at /mnt/d/it/work/blockchain/token-faucet/node_modules/@project-serum/anchor/src/coder/accounts.ts:28:39
    at Array.map (<anonymous>)

**Comment by sraymor17** [comment]
I am running into same issue, I tried changing my Idl json files, but they just get reassigned when I run the test.
