### ISSUE TITLE
Issue building Next.js app due to Webpack 5 incompatability

### ISSUE THREAD

**Issue by milorue** [project-serum/anchor#1552]
Hi, I'm currently working on implementing my staking protocol's frontend and I'm having issues with `next build` throwing this error
```
RangeError: Maximum call stack size exceeded
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:679:93)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:2060:92)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:679:93)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:2060:92)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:679:93)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:2060:92)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:679:93)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:2060:92)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:679:93)
    at Object.bM (/home/mrue/sites/staking/.next/server/pages/staking.js:2060:92) {
  type: 'RangeError'
```

Does anyone know what I need to do in Next.js to polyfill the native modules for anchor?

**Comment by fanatid** [comment]
I guess you need a custom webpack config. Please move your question to discord.
Maybe this will help: https://github.com/project-serum/anchor/issues/1516#issuecomment-1058397204
