### ISSUE TITLE
Error Number: 4100. Error Message: The declared program id does not match the actual program id.

### ISSUE THREAD

**Issue by rickiey** [project-serum/anchor#1599]
I used TOTURIAL in this step, and the result was a problem.

https://project-serum.github.io/anchor/tutorials/tutorial-0.html#generating-a-client

node client.js output:

```
Running client.
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1004 
    Program EqyEgYNGujjUyhgFYkzP9va2oFFw6rbyyp1AsbMnrt51 invoke [1]
    Program log: AnchorError occurred. Error Code: DeclaredProgramIdMismatch. Error Number: 4100. Error Message: The declared program id does not match the actual program id.
```

**Comment by callensm** [comment]
can you be a little more clear on the steps to reproduce the error, please?

**Comment by rickiey** [comment]
I understand, I have to declare program_id when I start writing code, so that it and the deployed program_id consistent
such as:
`declare_id!("AnLTG7X1FJRcnxVsKXMn7B6GrVuMn6xgxJ8TqTmbd7GP");`
`const programId = new anchor.web3.PublicKey("AnLTG7X1FJRcnxVsKXMn7B6GrVuMn6xgxJ8TqTmbd7GP");`

But I don't know how it is generated.

**Comment by callensm** [comment]
it may be that the keypair generated and written to `./target/deploy/<program>-keypair.json` is different that the public key you're asserting in the code with `declare_id`.

try copying the keypair file you _want_ to that path with the appropriate file name to ensure anchor is deploying with the same keypair that you're asserting and run it again.

**Comment by rickiey** [comment]
thx, I know how to do it.

**Comment by sn0rlacks** [comment]
Running into this as well. Any help is greatly appreciated as I feel very dumb

ENV: Debian 10 Buster
Node: 17.7.2
Python 3.9.11

My steps:

1. Deployment Output
```
Deploying workspace: http://localhost:8899
Upgrade authority: /home/admin/.config/solana/id.json
Deploying program "basic-0"...
Program path: /home/admin/dev/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so...
Program Id: 7yW4Yfi7E6f1DEZ7NLgxrWW4k9WFoWTeNh7ADWgduEeb
```

2. client.js code
```
  // Address of the deployed program.
  const programId = new anchor.web3.PublicKey("7yW4Yfi7E6f1DEZ7NLgxrWW4k9WFoWTeNh7ADWgduEeb");

  // Generate the program client from IDL.
  const program = new anchor.Program(idl, programId);

  // Execute the RPC.
  await program.rpc.initialize();
```

3. Attempt run
```
➜  basic-0 git:(master) ✗ ANCHOR_WALLET=/home/admin/.config/solana/id.json node client.js
Running client.
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1004
    Program 7yW4Yfi7E6f1DEZ7NLgxrWW4k9WFoWTeNh7ADWgduEeb invoke [1]
    Program log: AnchorError occurred. Error Code: DeclaredProgramIdMismatch. Error Number: 4100. Error Message: The declared program id does not match the actual program id.                                                                                  
    Program 7yW4Yfi7E6f1DEZ7NLgxrWW4k9WFoWTeNh7ADWgduEeb consumed 2511 of 1400000 compute units
    Program 7yW4Yfi7E6f1DEZ7NLgxrWW4k9WFoWTeNh7ADWgduEeb failed: custom program error: 0x1004
/home/admin/dev/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/error.js:54
            return new ProgramError(errorCode, errorMsg, errorCode + ": " + errorMsg);
                   ^

ProgramError: 4100: The declared program id does not match the actual program id
    at Function.parse (/home/admin/dev/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/error.js:54:20)
    at Object.rpc [as initialize] (/home/admin/dev/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:38:61)                                                                                                         
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/admin/dev/anchor/examples/tutorial/basic-0/client.js:24:3) {
  code: 4100,
  msg: 'The declared program id does not match the actual program id'
}
```

**Comment by yangyangpig** [comment]
@rickiey hello, how do you solve the issue, can you tell me?
