### ISSUE TITLE
Is the usage of `Init_if_needed` changed?

### ISSUE THREAD

**Issue by black-wyvern-dev** [project-serum/anchor#1614]
`    #[account(
        init_if_needed,
        seeds = [GLOBAL_AUTHORITY_SEED.as_ref()],
        bump = global_bump,
        payer = admin,
    )]
    pub global_authority: Account<'info, GlobalPool>,
`
I have coded like this. 
But when I test code, the below error appears.

`Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4 
    Program 28QKs5bDjJR7E3KKtXLW8K3gtP5LYqgEVkxXQBvQHCAK invoke [1]
    Program log: Instruction: Initialize
    Program log: Custom program error: 0xbc4
    Program 28QKs5bDjJR7E3KKtXLW8K3gtP5LYqgEVkxXQBvQHCAK consumed 3080 of 200000 compute units
    Program 28QKs5bDjJR7E3KKtXLW8K3gtP5LYqgEVkxXQBvQHCAK failed: custom program error: 0xbc4

/home/fury/Rust/apollo/FLOWERS-staking/staking/node_modules/@project-serum/anchor/src/error.ts:41
      return new ProgramError(errorCode, errorMsg, errorCode + ": " + errorMsg);
             ^
Error: 3012: The program expected this account to be already initialized
    at Function.parse (/home/fury/Rust/apollo/FLOWERS-staking/staking/node_modules/@project-serum/anchor/src/error.ts:41:14)
    at Object.rpc [as initialize] (/home/fury/Rust/apollo/FLOWERS-staking/staking/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:32:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by paul-schaaf** [comment]
init_if_needed has not changed in functionality (there have been bug fixes though)

if you need help with an error, pls take it to the discord https://discord.gg/aCUQvtwp
