### ISSUE TITLE
needs an import assertion of type

### ISSUE THREAD

**Issue by xiangjie256329** [project-serum/anchor#1683]
version 0.2.3 
anchor build
solana program deploy xxx.so
then anchor test will error,how to solve?

yarn run v1.22.17
warning package.json: No license field
$ /Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 tests/bpf-upgradable-state.ts

TypeError: Module "file:///Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/tsconfig.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:372:5)
      at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at formattedImport (/Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at Object.exports.requireOrImport (/Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at Object.exports.loadFilesAsync (/Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at singleRun (/Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/xiangjie/code/defi/solana/anchor/tests/bpf-upgradeable-state/node_modules/mocha/lib/cli/run.js:374:5)

**Comment by Aoi1011** [comment]
Run command
```
yarn add ts-mocha
```

I had same error. but I could finally test after hitting the above command.

**Comment by fanatid** [comment]
@Aoi1011 do we need to add `ts-mocha` to project template?

**Comment by matteosantama** [comment]
I just ran into this error too. Running `yarn add ts-mocha` resolved it. Comparing `yarn.lock` before and after, it looks like `ts-mocha` needed to get bumped from v8.0.0 to v10.0.0

**Comment by Mikerah** [comment]
Despite doing `yarn add ts-mocha`, I'm still getting this error. Oddly enough, the `anchor test` command was working previously
