### ISSUE TITLE
Tests in tutorial do not work anymore

### ISSUE THREAD

**Issue by jackcpku** [project-serum/anchor#1795]
It does not work when I run `yarn run test` in the `examples/tutorial/basic-0` directory.

- Platform: MacOS
- Version: 0.24.2

```

$ .../anchor/examples/tutorial/node_modules/.bin/mocha -t 1000000 tests/

Error: Cannot find module '.../anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (.../anchor/examples/tutorial/basic-0/tests/basic-0.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (.../anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (.../anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (.../anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
    at async singleRun (.../anchor/examples/tutorial/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (.../anchor/examples/tutorial/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.


```

I've tried the same command on version 0.24.0 and it worked fine.

**Comment by jackcpku** [comment]
It works when running `anchor test` as described [here](https://project-serum.github.io/anchor/tutorials/tutorial-0.html#workspaces)

**Comment by lucacertik** [comment]
How did you solve this problem?

**Comment by gww-certik** [comment]
To me it works:

```
Step 11/11 : RUN pwd && yarn install
 ---> Running in cdd8f49c809c
/anchor/examples/tutorial/basic-0
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.16s.
Removing intermediate container cdd8f49c809c
 ---> 143198d94686
Successfully built 143198d94686
```

I made such Dockerfile: https://gist.github.com/gww-certik/c22b40a3c2905dcac38a4fb7319bca5f and used `docker build .`

**Comment by 0xys** [comment]
Hi, I ran into the same issue.
Go to `anchor/ts` folder. Then run `yarn install` and `yarn build`. 
Hope this would help.
