### ISSUE TITLE
Anchor integration test doesn't exit when program panics

### ISSUE THREAD

**Issue by sohrab-** [project-serum/anchor#1842]
When running `anchor test`, if the program panics, the process hangs and does not exit.

It can be replicated by a simple program that say has a lot of un-boxed accounts so the access violation is thrown. Please see below an example of the log output.

The program just hangs after these logs forever. I waited up to 10 minutes before killing the process (successful test finishes in 9 seconds).

```
Found a 'test' script in the Anchor.toml. Running it as a test suite!

Running test suite: "/home/sohrab/workspaces/hello_anchor/Anchor.toml"

yarn run v1.22.18
$ /home/sohrab/workspaces/hello_anchor/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts


  hello
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS invoke [1]
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS consumed 3688 of 1400000 compute units
    Program failed to complete: Access violation in stack frame 3 at address 0x200003e38 of size 8 by instruction #4580
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS failed: Program failed to complete
    1) panics!


  0 passing (33ms)
  1 failing

  1) hello
       panics!:
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
      at Connection.sendEncodedTransaction (/home/sohrab/workspaces/common/temp/node_modules/.pnpm/@solana+web3.js@1.36.0/node_modules/@solana/web3.js/src/connection.ts:3964:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Connection.sendRawTransaction (/home/sohrab/workspaces/common/temp/node_modules/.pnpm/@solana+web3.js@1.36.0/node_modules/@solana/web3.js/src/connection.ts:3921:20)
      at async sendAndConfirmRawTransaction (/home/sohrab/workspaces/common/temp/node_modules/.pnpm/@project-serum+anchor@0.24.2/node_modules/@project-serum/anchor/src/provider.ts:284:21)
      at async AnchorProvider.sendAndConfirm (/home/sohrab/workspaces/common/temp/node_modules/.pnpm/@project-serum+anchor@0.24.2/node_modules/@project-serum/anchor/src/provider.ts:144:14)
      at async MethodsBuilder.rpc [as _rpcFn] (/home/sohrab/workspaces/common/temp/node_modules/.pnpm/@project-serum+anchor@0.24.2/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16)
      at async Context.<anonymous> (file:///home/sohrab/workspaces/hello_anchor/tests/hello.ts:84:5)
```

**Comment by fanatid** [comment]
Can you attach your test code and anchor program? Repo / branch with simple way to reproduce is preferred.

**Comment by sohrab-** [comment]
I set up a couple of different projects but can't seem to replicate it consistently. Def modifying the `tutorial-3` code to panic, it did not hang as I described above. But it is still happening in some of the other projects. 🤷 

For the sake hygiene, I'll close this for now till I can reliably reproduce it.
