### ISSUE TITLE
`anchor test` errors when program functions have a `u16` typed argument

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#216]
# Overview

`anchor test` appears to always fail when a program has a function that contains a `u16` typed argument.

# Error

```
     Error: Not yet implemented: [object Object]
      at Function.fieldLayout (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:280:27)
      at /media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:99:62
      at Array.map (<anonymous>)
      at /media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:99:40
      at Array.map (<anonymous>)
      at Function.parseIxLayout (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:98:38)
      at new InstructionCoder (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:67:42)
      at new Coder (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:49:28)
      at new Program (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/program.js:39:23)
      at /media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/workspace.js:39:34
      at Array.reduce (<anonymous>)
      at Object.get (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/workspace.js:35:18)
      at Context.<anonymous> (tests/test.js:10:38)
      at processImmediate (internal/timers.js:456:21)
```

# Reproduction Steps

1) run `anchor init`
2) change the default program to the following
```rust
use anchor_lang::prelude::*;

#[program]
pub mod test {
    use super::*;
    pub fn initialize(ctx: Context<Initialize>) -> ProgramResult {
        Ok(())
    }
    pub fn hello(ctx: Context<Initialize>, amount: u16) -> ProgramResult {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```
3) run `anchor test`

output from `anchor test`
```
$> anchor test
BPF SDK: /home/solidity/.local/share/solana/install/releases/1.6.6/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
warning: unused variable: `ctx`
 --> programs/test/src/lib.rs:6:23
  |
6 |     pub fn initialize(ctx: Context<Initialize>) -> ProgramResult {
  |                       ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `ctx`
 --> programs/test/src/lib.rs:9:18
  |
9 |     pub fn hello(ctx: Context<Initialize>, amount: u16) -> ProgramResult {
  |                  ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`

warning: unused variable: `amount`
 --> programs/test/src/lib.rs:9:44
  |
9 |     pub fn hello(ctx: Context<Initialize>, amount: u16) -> ProgramResult {
  |                                            ^^^^^^ help: if this is intentional, prefix it with an underscore: `_amount`

warning: 3 warnings emitted

    Finished release [optimized] target(s) in 0.06s

To deploy this program:
  $ solana program deploy /media/solidity/DATA1/Code/sol-farm/test/target/deploy/test.so


  test
    1) Is initialized!


  0 passing (57ms)
  1 failing

  1) test
       Is initialized!:
     Error: Not yet implemented: [object Object]
      at Function.fieldLayout (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:280:27)
      at /media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:99:62
      at Array.map (<anonymous>)
      at /media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:99:40
      at Array.map (<anonymous>)
      at Function.parseIxLayout (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:98:38)
      at new InstructionCoder (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:67:42)
      at new Coder (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/coder.js:49:28)
      at new Program (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/program.js:39:23)
      at /media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/workspace.js:39:34
      at Array.reduce (<anonymous>)
      at Object.get (/media/solidity/DATA1/Code/node_modules/@project-serum/anchor/dist/cjs/workspace.js:35:18)
      at Context.<anonymous> (tests/test.js:10:38)
      at processImmediate (internal/timers.js:456:21)


```

**Comment by bonedaddy** [comment]
this was solved in v0.5.0
