### ISSUE TITLE
Tutorial-0 test failure

### ISSUE THREAD

**Issue by jon-chuang** [project-serum/anchor#260]
Fails with 
```
0 passing (33ms)
  1 failing

  1) basic-0
       Uses the workspace to invoke the initialize instruction:
     TypeError: accounts.map(...).flat is not a function
      at Function.accountsArray (/home/jonch/.nvm/versions/node/v10.22.0/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:207:14)
      at ix (/home/jonch/.nvm/versions/node/v10.22.0/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:169:37)
      at txFn (/home/jonch/.nvm/versions/node/v10.22.0/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:237:20)
      at Object.rpc [as initialize] (/home/jonch/.nvm/versions/node/v10.22.0/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:212:24)
      at Context.it (tests/basic-0.js:13:23)

```
on current master

**Comment by armaniferrante** [comment]
Update your node version. CI runs 14.7 at the moment.
