### ISSUE TITLE
test basic-0 and basic-1 fail

### ISSUE THREAD

**Issue by jon-chuang** [project-serum/anchor#261]
fails with the following errors:
```
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. 
    
Translating error Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4518:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4479:20)
    at async Object.sendAndConfirmRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6177:21)
    at async Provider.send (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:52:22)
    at async Object.rpc [as initialize] (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:215:31)
    at async Context.<anonymous> (/home/jonch/Desktop/Programming/blockchain/anchor/examples/tutorial/basic-0/tests/basic-0.js:13:5)
    1) Uses the workspace to invoke the initialize instruction


  0 passing (95ms)
  1 failing

  1) basic-0
       Uses the workspace to invoke the initialize instruction:
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

```
 basic-1
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. 
    
    1) Creates and initializes an account in two different transactions
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. 
    
Translating error Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4518:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4479:20)
    at async Object.sendAndConfirmRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6177:21)
    at async Provider.send (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:52:22)
    at async Object.rpc [as initialize] (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:215:31)
    at async Context.<anonymous> (/home/jonch/Desktop/Programming/blockchain/anchor/examples/tutorial/basic-1/tests/basic-1.js:64:5)
    2) Creates and initializes an account in a single atomic transaction
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. 
    
Translating error Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4518:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4479:20)
    at async Object.sendAndConfirmRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6177:21)
    at async Provider.send (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:52:22)
    at async Object.rpc [as initialize] (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/rpc.js:215:31)
    at async Context.<anonymous> (/home/jonch/Desktop/Programming/blockchain/anchor/examples/tutorial/basic-1/tests/basic-1.js:100:5)
    3) Creates and initializes an account in a single atomic transaction (simplified)
    4) Updates a previously created account


  0 passing (164ms)
  4 failing

  1) basic-1
       Creates and initializes an account in two different transactions:
     Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
      at Connection.sendEncodedTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4518:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Connection.sendRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4479:20)
      at async Object.sendAndConfirmRawTransaction (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6177:21)
      at async Provider.send (/home/jonch/.nvm/versions/node/v14.16.1/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:52:22)
      at async Context.<anonymous> (tests/basic-1.js:33:5)

  2) basic-1
       Creates and initializes an account in a single atomic transaction:
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) basic-1
       Creates and initializes an account in a single atomic transaction (simplified):
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) basic-1
       Updates a previously created account:
     TypeError: Cannot read property 'publicKey' of undefined
      at Context.<anonymous> (tests/basic-1.js:131:30)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by jon-chuang** [comment]
OK, it passes when I shut down `solana-test-validator`.

Is this expected behaviour?

**Comment by armaniferrante** [comment]
Yes. If one wants to run tests against a separate localnet one can use `anchor test --skip-localnet`, though the programs must be deployed/embedded into the other validator for the tests above to run successfully.

**Comment by AlbanMinassian** [comment]
`anchor test --skip-local-validator` with last version
