### ISSUE TITLE
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x63 

### ISSUE THREAD

**Issue by vigneshka** [project-serum/anchor#327]
Receiving the following error when following the getting started guide for the basic-0 example. Any help would be greatly appreciated!

```
vignesh@vignesh-laptop:~/workspace/anchor/examples/tutorial/basic-0$ anchor test
BPF SDK: /home/vignesh/.local/share/solana/install/releases/1.6.10/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.27s

To deploy this program:
  $ solana program deploy /home/vignesh/workspace/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so


  basic-0
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x63 
    Program HV2wF58ztCavtX3s89cQzMQRvhhLzg1Wpq4yU3gDbDRg invoke [1]
    Program log: Fallback functions are not supported. If you have a use case, please file an issue.
    Program log: Custom program error: 0x63
    Program HV2wF58ztCavtX3s89cQzMQRvhhLzg1Wpq4yU3gDbDRg consumed 1626 of 200000 compute units
    Program HV2wF58ztCavtX3s89cQzMQRvhhLzg1Wpq4yU3gDbDRg failed: custom program error: 0x63
Translating error Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x63
    at Connection.sendEncodedTransaction (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4623:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4584:20)
    at async Object.sendAndConfirmRawTransaction (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6369:21)
    at async Provider.send (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:81:22)
    at async Object.rpc [as initialize] (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:12:31)
    at async Context.<anonymous> (/home/vignesh/workspace/anchor/examples/tutorial/basic-0/tests/basic-0.js:13:5)
    1) Uses the workspace to invoke the initialize instruction


  0 passing (182ms)
  1 failing

  1) basic-0
       Uses the workspace to invoke the initialize instruction:
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x63
      at Connection.sendEncodedTransaction (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4623:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Connection.sendRawTransaction (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4584:20)
      at async Object.sendAndConfirmRawTransaction (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6369:21)
      at async Provider.send (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:81:22)
      at async Object.rpc [as initialize] (/home/vignesh/.nvm/versions/node/v14.17.0/lib/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:12:31)
      at async Context.<anonymous> (tests/basic-0.js:13:5)
```

**Comment by vigneshka** [comment]
**Update:** 
The examples in master are currently broken. Checkout the 0.60 tag and it should work.
```git checkout tags/v0.6.0```

**Comment by armaniferrante** [comment]
Note that the examples in master work, but they require the tools on master, which are part of the next `v0.7.0` release.

**Comment by vigneshka** [comment]
Ah I see. The dependencies reference v0.6.0, but the examples reference the master repo https://project-serum.github.io/anchor/tutorials/tutorial-0.html.

**Comment by armaniferrante** [comment]
Great point. I'll re-open this for now. In the future we'll probably want to use a separate branch for merging breaking changes so that the examples continue to work.

**Comment by armaniferrante** [comment]
This was completed in v0.7.0.
