### ISSUE TITLE
Error when running "anchor test" :Cannot find module '@project-serum/anchor'

### ISSUE THREAD

**Issue by patrick-fitzgerald** [project-serum/anchor#338]
Hi, I'm having an issue running the anchor examples.
I've followed the instructions in https://project-serum.github.io/anchor/getting-started/installation.html and https://github.com/project-serum/anchor/issues/327

```
git checkout tags/v0.6.0
```
My node version
```
basic-1 git:(6da6ae2) ✗ node --version
v16.2.0
```

```
basic-1 git:(6da6ae2) ✗ npm install -g @project-serum/anchor
+ @project-serum/anchor@0.6.1-beta.1
updated 1 package in 2.953s
```

``` 
basic-1 git:(6da6ae2) ✗ npm install -g mocha
/usr/local/bin/_mocha -> /usr/local/lib/node_modules/mocha/bin/_mocha
/usr/local/bin/mocha -> /usr/local/lib/node_modules/mocha/bin/mocha
+ mocha@8.4.0
updated 1 package in 3.776s
```

When running `anchor test` in `anchor/examples/tutorial/basic-1` I see this error:
```
 basic-1 git:(6da6ae2) ✗ anchor test
BPF SDK: /Users/paddy/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.15s

To deploy this program:
  $ solana program deploy /Users/paddy/dev/crypto/solana/anchor/examples/tutorial/basic-1/target/deploy/basic_1.so

Error: Cannot find module '@project-serum/anchor'
Require stack:
- /Users/paddy/dev/crypto/solana/anchor/examples/tutorial/basic-1/tests/basic-1.js
- /usr/local/lib/node_modules/mocha/lib/esm-utils.js
- /usr/local/lib/node_modules/mocha/lib/mocha.js
- /usr/local/lib/node_modules/mocha/lib/cli/one-and-dones.js
- /usr/local/lib/node_modules/mocha/lib/cli/options.js
- /usr/local/lib/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/paddy/dev/crypto/solana/anchor/examples/tutorial/basic-1/tests/basic-1.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.exports.requireOrImport (/usr/local/lib/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/usr/local/lib/node_modules/mocha/lib/cli/run.js:362:11)
    at /usr/local/lib/node_modules/mocha/node_modules/yargs/build/index.cjs:443:71
```

Any ideas how to fix this issue?

Thanks

**Comment by armaniferrante** [comment]
The error message suggests your `NODE_PATH` isn't set correctly.

**Comment by patrick-fitzgerald** [comment]
Thanks. It looks like it was an issue with how nvm was setup.
I got it to work by using: `export NODE_PATH="$(npm config get prefix)/lib/node_modules"`
