### ISSUE TITLE
anchor build -- Error Anchor not found

### ISSUE THREAD

**Issue by mukeshmediratta1966** [project-serum/anchor#635]
I went thru all the steps mentioned in 
https://project-serum.github.io/anchor/getting-started/introduction.html

I an using UBUNTU on Windiws 10..

But getting error here.. please help

mukeshmediratta@DESKTOP-023N740:~$ cd anchor/examples/tutorial/basic-0
mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$ anchor build

Command 'anchor' not found, did you mean:

  command 'anchors' from deb lagan (2.0-5build1)

Try: sudo apt install <deb name>

**Comment by armaniferrante** [comment]
Did you try installing via cargo? https://project-serum.github.io/anchor/getting-started/installation.html#install-anchor

**Comment by mukeshmediratta1966** [comment]
mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$ anchor deploy
Deploying workspace: http://127.0.0.1:8899
Upgrade authority: /home/mukeshmediratta/.config/solana/id.json
Deploying program "basic-0"...
Program path: /home/mukeshmediratta/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so...
Program Id: 3Eb45dDCHKDh4weBkxErZdEqk3zGUwqtvjy3T5Mse9mU

Deploy success
mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$ node client.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '@project-serum/anchor'
Require stack:
- /home/mukeshmediratta/anchor/examples/tutorial/basic-0/client.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/mukeshmediratta/anchor/examples/tutorial/basic-0/client.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mukeshmediratta/anchor/examples/tutorial/basic-0/client.js'
  ]
}

After deploying now unable to run the client

**Comment by mukeshmediratta1966** [comment]
> Did you try installing via cargo? https://project-serum.github.io/anchor/getting-started/installation.html#install-anchor

Yes.. now it seems to be working some how..
