### ISSUE TITLE
The tutorial client.js file makes an error: Translating error Error: failed to get recent blockhash

### ISSUE THREAD

**Issue by CryptoDogg** [project-serum/anchor#682]
I am following the tutorial https://project-serum.github.io/anchor/tutorials/tutorial-0.html. 
When I run ` $ node client.js`, I get the following error.
```
Running client.
Translating error Error: failed to get recent blockhash: FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899
    at Connection.getRecentBlockhash (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4305:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:420283) UnhandledPromiseRejectionWarning: Error: failed to get recent blockhash: FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899
    at Connection.getRecentBlockhash (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4305:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:420283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:420283) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Could anyone help me?

**Comment by armaniferrante** [comment]
Are you running a local network via `solana-test-validator` ?

**Comment by CryptoDogg** [comment]
Thank you for your reply. 
I was not running the validator. 

After runnning `solana-test-validator`, then running client.js, I got another error following.
```
Running client.
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. 
    
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4881:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Connection.sendRawTransaction (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4840:20)
    at async Object.sendAndConfirmRawTransaction (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6730:21)
    at async Provider.send (/usr/local/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initialize] (/usr/local/lib/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
    at async main (/home/usr/projects/anchor/examples/tutorial/basic-0/client.js:22:3) {
  logs: []
}
(node:426291) UnhandledPromiseRejectionWarning: Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4881:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Connection.sendRawTransaction (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:4840:20)
    at async Object.sendAndConfirmRawTransaction (/usr/local/lib/node_modules/@project-serum/anchor/node_modules/@solana/web3.js/lib/index.cjs.js:6730:21)
    at async Provider.send (/usr/local/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initialize] (/usr/local/lib/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
    at async main (/home/usr/projects/anchor/examples/tutorial/basic-0/client.js:22:3)
(node:426291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:426291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by armaniferrante** [comment]
Did you run `solana-keygen new` and `anchor deploy`? For further assistance, please join the discord. Closing as this doesn't appear to be a development issue.

**Comment by keshrisohit** [comment]
I am also getting the same error.

**Comment by YikSanChan** [comment]
> Did you run `solana-keygen new` and `anchor deploy`? For further assistance, please join the discord. Closing as this doesn't appear to be a development issue.

Discord doesn't even have "thread". And for this reason it is pretty bad for question answering imo
