### ISSUE TITLE
Tutorial basic-1 builds but fails test/deploy with "associated or seeds must be provided before payer" error

### ISSUE THREAD

**Issue by ptudan** [project-serum/anchor#731]
Working through the tutorials, I'm getting a weird combination of success/failure when building, then complete failure when deploy/testing.

```
paul@DESKTOP:~/environments/soltest/anchor/examples/tutorial/basic-1$ anchor build
BPF SDK: /home/paul/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
   Compiling anyhow v1.0.44
...
   Compiling basic-1 v0.1.0 (/home/paul/environments/soltest/anchor/examples/tutorial/basic-1/programs/basic-1)
    Finished release [optimized] target(s) in 7.99s
Running: /home/paul/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/scripts/strip.sh /home/paul/environments/soltest/anchor/examples/tutorial/basic-1/target/bpfel-unknown-unknown/release/basic_1.so /home/paul/environments/soltest/anchor/examples/tutorial/basic-1/target/deploy/basic_1.so
Running: /home/paul/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/paul/environments/soltest/anchor/examples/tutorial/basic-1/target/deploy/basic_1.so

To deploy this program:
  $ solana program deploy /home/paul/environments/soltest/anchor/examples/tutorial/basic-1/target/deploy/basic_1.so
thread 'main' panicked at 'Code not parseable: Error("associated or seeds must be provided before payer")', lang/syn/src/idl/file.rs:337:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

What's confusing to me here is that the build is completing, as I'm getting the CLI output for the solana deploy command, but then the thread panic error comes.  Running this deploy command _works_!

Running anchor deploy or test gives just the errors.

`paul@DESKTOP:~/environments/soltest/anchor/examples/tutorial/basic-1$ anchor test
thread 'main' panicked at 'Code not parseable: Error("associated or seeds must be provided before payer")', lang/syn/src/idl/file.rs:337:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

The error is in the account attribute used below:

```
#[derive(Accounts)]
pub struct Initialize<'info> {  
    #[account(init, payer = user, space = 8 + 8)]
    pub my_account: Account<'info, MyAccount>,
    pub user: AccountInfo<'info>,
    pub system_program: AccountInfo<'info>,
}
```

https://docs.rs/anchor-lang/0.11.1/anchor_lang/derive.Accounts.html  These are the relevant docs.  I honestly don't know enough to understand them at this point.  What are seeds?  I will submit a PR fixing this tutorial if someone can help me fix this issue.

**Comment by ptudan** [comment]
Updated my anchor/solana clis and pulled the latest repo.  Now it errors on builds and tests.  The build still spits out a solana deploy command that works.

The error is now different, it is:

`thread 'main' panicked at 'Could not resolve Accounts symbol', lang/syn/src/idl/file.rs:451:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
