### ISSUE TITLE
Error running `anchor test` - TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by camchis** [project-serum/anchor#812]
I have followed the installation instructions here https://project-serum.github.io/anchor/getting-started/installation.html and am receiving an error when running `anchor test` on the `basic-0` program in the tutorial files

node version: `14.18.0`
npm version: `6.14.15`
mocha version: `9.1.2`
anchor version: `0.16.2`

I am getting the following error:

```
cameron@Cameron basic-0 % anchor test          
BPF SDK: /Users/cameron/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.34s
Running: /Users/cameron/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /Users/cameron/Desktop/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so

To deploy this program:
  $ solana program deploy /Users/cameron/Desktop/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:489:10)
    at Object.readFileSync (fs.js:393:35)
    at Function.local (/usr/local/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:154:92)
    at Function.local (/usr/local/lib/node_modules/@project-serum/anchor/dist/cjs/provider.js:38:35)
    at Suite.<anonymous> (/Users/cameron/Desktop/anchor/examples/tutorial/basic-0/tests/basic-0.js:5:38)
    at Object.create (/usr/local/lib/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/usr/local/lib/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/Users/cameron/Desktop/anchor/examples/tutorial/basic-0/tests/basic-0.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async formattedImport (/usr/local/lib/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/usr/local/lib/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
    at async singleRun (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/usr/local/lib/node_modules/mocha/lib/cli/run.js:374:5)
```

**Comment by joaoh82** [comment]
why was this closed, if it is obviously not solved?

**Comment by bricestacey** [comment]
I ran into this myself. You can find fix in this PR https://github.com/project-serum/anchor/pull/832
