### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by Devplex** [project-serum/anchor#988]
When I run anchor test on this test script:
const anchor = require('@project-serum/anchor');

const { SystemProgram } = anchor.web3;

const main = async () => {
  console.log("Starting the test!");

  const provider = anchor.Provider.env();
}

const runMain = async () => {
  try {
    await main();
    process.exit(0);
  } catch (e) {
    console.error(e);
    process.exit(1)
  }
};

runMain();

It prints the console.log but then exists with the following error:
`ReferenceError: TextEncoder is not defined
at Function.fromSecretKey (/home/devplex/Documents/FirstSolanaDapp/firstSolanaDapp/trade_x/node_modules/@solana/web3.js/lib/index.cjs.js:7320:23)
    at Function.local (/home/devplex/Documents/FirstSolanaDapp/firstSolanaDapp/trade_x/node_modules/@project-serum/anchor/dist/cjs/provider.js:154:41)
    at Function.env (/home/devplex/Documents/FirstSolanaDapp/firstSolanaDapp/trade_x/node_modules/@project-serum/anchor/dist/cjs/provider.js:58:35)
    at main (/home/devplex/Documents/FirstSolanaDapp/firstSolanaDapp/trade_x/tests/trade_x.js:8:36)
    at runMain (/home/devplex/Documents/FirstSolanaDapp/firstSolanaDapp/trade_x/tests/trade_x.js:39:11)
    at Object.<anonymous> (/home/devplex/Documents/FirstSolanaDapp/firstSolanaDapp/trade_x/tests/trade_x.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.implementationOfRequireOrImportForUnstableEsm [as requireOrImport] (/usr/local/lib/node_modules/mocha/lib/nodejs/esm-utils.js:101:12)
    at Object.exports.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/nodejs/esm-utils.js:88:34)
    at Mocha.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/mocha.js:461:19)
    at singleRun (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/usr/local/lib/node_modules/mocha/lib/cli/run.js:374:11)
    at innerArgv.then.argv (/usr/local/lib/node_modules/mocha/node_modules/yargs/build/index.cjs:443:71)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at findNodeScript.then.existing (/usr/share/nodejs/libnpx/index.js:268:14)`

**Comment by arunprasath2007** [comment]
Hi, I'm facing this issue today morning. Can you let me know how did you solve this error?

![image](https://user-images.githubusercontent.com/1463927/140693478-b9853970-dfc2-43b5-abaa-d66dbd196d52.png)

**Comment by Devplex** [comment]
Updating Node to the latest version solved it for me.
